const reviews = [
  {
    id: 1,
    name: "John Doe",
    avatar: "https://randomuser.me/api/portraits",
    text: "This is a review",
    rating: Number(5),
    likes: 0,
    replies: [],
  },
  {
    id: 2,
    name: "Jane Doe",
    avatar: "https://randomuser.me/api/portraits",
    text: "This is another review",
    likes: 0,
    rating: Number(5),
    replies: [],
  },
  {
    id: 3,
    name: "John Smith",
    avatar: "https://randomuser.me/api/portraits",
    text: "This is a review",
    likes: 0,
    rating: Number(5),
    replies: [],
  },
  {
    id: 4,
    name: "Jane Smith",
    avatar: "https://randomuser.me/api/portraits",
    text: "This is another review",
    likes: 0,
    rating: Number(5),
    replies: [],
  },
  {
    id: 5,
    name: "John Doe",
    avatar: "https://randomuser.me/api/portraits",
    text: "This is a review",
    likes: 0,
    rating: Number(5),
    replies: [],
  },
  {
    id: 6,
    name: "Jane Doe",
    avatar: "https://randomuser.me/api/portraits",
    text: "This is another review",
    likes: 0,
    rating: Number(5),
    replies: [],
  },
  {
    id: 7,
    name: "John Smith",
    avatar: "https://randomuser.me/api/portraits",
    text: "This is a review",
    likes: 0,
    rating: Number(5),
    replies: [],
  },
  {
    id: 8,
    name: "Jane Smith",
    avatar: "https://randomuser.me/api/portraits",
    text: "This is another review",
    likes: 0,
    rating: Number(5),
    replies: [],
  },
  {
    id: 9,
    name: "John Doe",
    avatar: "https://randomuser.me/api/portraits",
    text: "This is a review",
    likes: 0,
    rating: Number(5),
    replies: [],
  },
  {
    id: 10,
    name: "Jane Doe",
    avatar: "https://randomuser.me/api/portraits",
    text: "This is another review",
    likes: 0,
    rating: Number(5),
    replies: [],
  },
  {
    id: 11,
    name: "John Smith",
    avatar: "https://randomuser.me/api/portraits",
    text: "This is a review",
    likes: 0,
    rating: Number(5),
    replies: [],
  },
  {
    id: 12,
    name: "Jane Smith",
    avatar: "https://randomuser.me/api/portraits",
    text: "This is another review",
    likes: 0,
    rating: Number(5),
    replies: [],
  },
];

export default reviews;
